---
title: "Critical evaluation of the reliability of DNA methylation probes on the Illumina MethylationEPIC BeadChip microarrays for dementia research"
subtitle: "ICC calculation"
author: "Wei Zhang, Lily Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
    font_size: 10
editor_options:
  chunk_output_type: inline 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
dir.base <- "../../"
dir.data.new <- file.path(dir.base, "data/ADNI/")
dir.raw.selected <-  file.path(dir.data.new, "/DNA_methylation/raw/")
dir.RnBeads.selected <- file.path(dir.data.new, "/DNA_methylation/RnBeads/")
dir.data.new.processed <- file.path(dir.data.new, "/DNA_methylation/processed/")
dir.reliable.score <- file.path(dir.base, "/analysis-results/reliable_score_different_plate/")
```

```{r eval = F}
beta <- readRDS( file.path(dir.data.new.processed,"ADNI_RnBeads_and_pooBAH_filtered_beta_different_plates.RDS"))
samples.duplicated.all <- readxl::read_xlsx(
  file.path(dir.data.new.processed, "ADNI_DNA_Methylation_Sample_Duplicated_IND.xlsx")
)
## Select samples with different plates
samples.diff.plate.slide <- samples.duplicated.all %>% 
  dplyr::select(RID, PlateNumber) %>% unique %>% group_by(RID) %>% 
  dplyr::summarise(n = n()) %>% filter(n == 2)
samples.duplicated.ind <- samples.duplicated.all %>% filter(RID %in% samples.diff.plate.slide$RID)
samples.id <- samples.duplicated.ind %>% dplyr::select(RID_Phase_Edata, barcodes) %>% 
  dplyr::group_by(RID_Phase_Edata) %>% 
  dplyr::mutate(obs = dplyr::row_number()) %>% 
  pivot_wider(names_from = "obs", 
              values_from = "barcodes", 
              names_prefix="barcodes")
```

```{r eval = F}
## Auxillary function
source("../Utility.R")
```

```{r eval = F}
## Beta
reliable_score_single <- create_rating(samples.id, beta, unit = "single")
colnames(reliable_score_single)[1] <- "cpg"
## M
M <- minfi::logit2(beta)
reliable_score_single.M <- create_rating(samples.id, M, unit = "single")
colnames(reliable_score_single.M)[1] <- "cpg"
```

```{r eval = F}
write_csv(
  reliable_score_single %>% arrange(desc(value)),
  file.path(dir.reliable.score, "ADNI_sesame_icc_results_ind_measure_single_different_plate.csv")
)
write_csv(
  reliable_score_single.M %>% arrange(desc(value)),
  file.path(dir.reliable.score, "ADNI_sesame_icc_results_ind_measure_single_M_values_different_plate.csv")
)
```

# Session Information

```{r}
devtools::session_info()
```