---
title: "Critical evaluation of the reliability of DNA methylation probes on the Illumina MethylationEPIC BeadChip microarrays for dementia research"
subtitle: "Cell type proportion ICC"
author: "Wei Zhang, Lily Wang"
date: "`r Sys.Date()`"
output:
  html_document:
    highlight: pygments
    theme: yeti
    toc: true
    number_sections: true
    df_print: paged
    code_download: false
    toc_float:
      collapsed: yes
    toc_depth: 3
    font_size: 10
editor_options:
  chunk_output_type: inline 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(irr)

dir.base <- "../../"
dir.data.new <- file.path(dir.base, "data/ADNI")
dir.data.new.processed <- file.path(dir.data.new, "DNA_methylation/processed")
dir.cell.type <- file.path(dir.base, "analysis-results/cell_type")
dir.plot <- file.path(dir.base, "analysis-results/plots")

dir.achintya <- file.path(dir.base, "Achintya")
for(p in grep("dir",ls(),value = T)) dir.create(get(p),recursive = TRUE,showWarnings = FALSE)
```

```{r}
# Load auxilary function
source("../Utility.R")
```

# Load results

```{r message = F}
sample1 <- read_csv(
  file.path(dir.achintya, "sample_one_cell_proportions.csv")
)[,-9] # remove geo number
colnames(sample1)[1] <- "barcodes"
sample2 <- read_csv(
  file.path(dir.achintya, "sample_two_cell_proportions.csv")
)
colnames(sample2)[1] <- "barcodes"
cell_type <- rbind(sample1, sample2) %>% column_to_rownames("barcodes") %>% t()
colnames(cell_type) <- gsub("^X", "", colnames(cell_type))
# sample information
samples.duplicated <- readxl::read_xlsx(
  file.path(dir.data.new.processed, "ADNI_DNA_Methylation_Sample_Duplicated_Diff_Plates.xlsx")
)
samples.id <- samples.duplicated %>% dplyr::select(RID_Phase_Edata, barcodes) %>% 
  dplyr::group_by(RID_Phase_Edata) %>% 
  dplyr::mutate(obs = dplyr::row_number()) %>% 
  pivot_wider(names_from = "obs", 
              values_from = "barcodes", 
              names_prefix="barcodes")
```

# ICC compute

```{r}
reliable_cell_type <- create_rating(samples.id, cell_type, unit = "single", id = "cell_type")
colnames(reliable_cell_type)[2] <- "ICC"
reliable_cell_type
```

```{r eval = F}
write_csv(reliable_cell_type, file.path(dir.cell.type, "cell_type_ICC.csv"))
```

# Session information

```{r}
devtools::session_info()
```

